# https://github.com/salvogiangri/UN1CA/blob/sixteen/unica/patches/__floating_feature/customize.sh
# UN1CA floating_feature patch
# Author: @salvogiangri
# - Add deprecated features in the $DEPRECATED variable
# - Add features to ignore in the $BLACKLIST variable
# - Add default values for missing features in the $FALLBACK variable

DEPRECATED="
AUDIO_CONFIG_FMRADIO_EXTERNAL_DEVICE
AUDIO_CONFIG_VOLUMEMONITOR_PHASE
BATTERY_SUPPORT_WIRELESS_TX_5V_TA
BIXBY_SUPPORT_USERKWD_WAKEUP
COMMON_CONFIG_DEX_MODE
COMMON_CONFIG_DUAL_IMS
COMMON_SUPPORT_CONVENTIONAL_MODE
COMMON_SUPPORT_D2D_NUMBER_TRANSFER_SEND_ONLY
COMMON_SUPPORT_DEX_ON_PC
COMMON_SUPPORT_EMBEDDED_SIM
COMMON_SUPPORT_EPDG_CROSS_SIM
COMMON_SUPPORT_KNOX_DESKTOP
COMMON_SUPPORT_SAFETYCARE
COMMON_SUPPORT_SPEN_ALERT
FMRADIO_CONFIG_COMMON_SUPPORT_HYBRIDSEARCH
FMRADIO_REMOVE_AF_MENU
FRAMEWORK_CONFIG_EDGE_QUICKTOOLS_SCREEN_HEIGHT
FRAMEWORK_CONFIG_SCREEN_RECORDER_ITEM
FRAMEWORK_SUPPORT_AUTO_ROTATION_OF_SMARTWIDGET
FRAMEWORK_SUPPORT_EAGLE_EYE
GALLERY_CONFIG_COLOR_ENGINE_VERSION
GALLERY_SUPPORT_LOCATION_POI
LOCKSCREEN_SUPPORT_VIDEO_PLAY_RANDOM_POSITION
MMFW_CONFIG_SMART_MIRRORING_PACKAGE_NAME
MMFW_SUPPORT_AI_UPSCALER
MMFW_SUPPORT_MTK_SSM_SM_VIDEO
MMFW_SUPPORT_MUSIC_AUTO_RECOMMENDATION
SAIV_CONFIG_BEAUTY_FACE
SETTINGS_SUPPORT_S_PEN_HOVERING_N_DETACHMENT
SIP_CONFIG_STICKER_CONTENTS
SIP_SUPPORT_DIRECT_WRITING_ENABLE
WEATHER_SUPPORT_DETAIL_CITY_VIEW
WIFI_SUPPORT_ADPS
WLAN_SUPPORT_SECURE_WIFI
"

BLACKLIST="
AUDIO_CONFIG_ASSISTANT_SPEAKER_MAX_VOLUME
BIXBY_CONFIG_BARGEIN_PARAM_MODE
CAMERA_CONFIG_ACTION_CLASSIFIER
CAMERA_CONFIG_AI_DEFLICKER
CAMERA_CONFIG_MOIRE_REMOVAL
CAMERA_CONFIG_MOTIONPHOTO_DEFAULT_SOUND_TIMING
CAMERA_CONFIG_MOTIONPHOTO_DEFAULT_SOUND_TYPE
CAMERA_CONFIG_MYFILTER
CAMERA_CONFIG_STRIDE_OCR_VERSION
CAMERA_CONFIG_SUPERSTEADY_POPUP
CAMERA_CONFIG_VERSION_FILTER_PROVIDER
CAMERA_DOCUMENTSCAN_SOLUTIONS
CAMERA_SUPPORT_AI_HIGH_RESOLUTION_DRAFT_DOWNSCALE
CAMERA_SUPPORT_CONTROLLING_WATCH
CAMERA_SUPPORT_PRIVACY_TOGGLE
COMMON_CONFIG_AI_VERSION
COMMON_CONFIG_AWESOME_INTELLIGENCE
COMMON_CONFIG_EDGE
COMMON_CONFIG_MULTIMEDIA_EDITOR_PLUGIN_PACKAGES
COMMON_CONFIG_SEP_CATEGORY
COMMON_CONFIG_SMARTTUTOR_PACKAGES_PATH
COMMON_DISABLE_NATIVE_AI
COMMON_SUPPORT_AI_AGENT
COMMON_SUPPORT_DESKTOP_WINDOWING
COMMON_SUPPORT_LTW_REMOTE_APP
CONTEXTSERVICE_ENABLE_SURVEY_MODE
DWB_CONFIG_UNSUSPENDABLE_PACKAGE_NAME
FACTORY_CONFIG_PART_REPLACEMENT_HISTORY
FMRADIO_CONFIG_AVOID_REGION
FRAMEWORK_CONFIG_AOD_ITEM
FRAMEWORK_SUPPORT_PERSONALIZED_DATA_CORE
FRAMEWORK_SUPPORT_SCREEN_RECORDER
FRAMEWORK_SUPPORT_SMART_SUGGESTIONS_WIDGET
FRAMEWORK_SUPPORT_STACK_WIDGET_AUTO_ROTATION
GALLERY_CONFIG_FACE_CLUSTER_VERSION
GALLERY_CONFIG_IMAGE_TAGGER_VERSION
GALLERY_CONFIG_PBE
GALLERY_CONFIG_PET_CLUSTER_VERSION
GALLERY_SUPPORT_SPC_LOCATION_POI
GALLERY_SUPPORT_STORYEDITOR
GENAI_SUPPORT_C2PA
GENAI_SUPPORT_IMAGE_CLIPPER
GENAI_SUPPORT_OBJECT_ERASER
GENAI_SUPPORT_REFLECTION_ERASER
GENAI_SUPPORT_SHADOW_ERASER
GENAI_SUPPORT_SMART_LASSO
GENAI_SUPPORT_SPOT_FIXER
GENAI_SUPPORT_STYLE_TRANSFER
GPS_CONFIG_SUPL_VENDOR
GRAPHICS_CONFIG_GAMEBOOSTER_SUICIDE_INTERVAL_MS
GRAPHICS_SUPPORT_3D_SURFACE_TRANSITION_FLAG
GRAPHICS_SUPPORT_GAMEBOOSTER_MANUAL_ROUTINE
GRAPHICS_SUPPORT_GAME_SERVER_POLICY_QUERIES
GRAPHICS_SUPPORT_RELUMINO_EFFECT_FLAG
HWR_CONFIG_RECOGNITION_SUPPORT
LAUNCHER_CONFIG_ANIMATION_TYPE
LAUNCHER_CONFIG_ZERO_PAGE_PACKAGE_NAMES
MSCH_SUPPORT_NLSEARCH
RIL_CONFIG_DM_OPERATOR
SAIV_CONFIG_AI_REVITAL_VERSION
SAIV_CONFIG_ARDOODLE_LIB
SAIV_CONFIG_MIDAS
SAIV_SUPPORT_3DPHOTO
SMART_VIEW_APP_CAST_SUPPORTED
SYSTEMUI_CONFIG_EDGELIGHTING_FRAME_EFFECT
SYSTEM_SUPPORT_SCREEN_CURTAIN
VISION_CONFIG_IMAGE_TRANSLATION_OVERLAY_VERSION
VISION_SUPPORT_AI_MY_FAVORITE_CONTENTS
"

FALLBACK="
AUDIO_CONFIG_INTERPRETER 0
CAMERA_CONFIG_MOTIONPHOTO_CAPTURE_MODE [[3,1]]
CAMERA_CONFIG_QRCODE_INTERVAL 500
CAMERA_CONFIG_UW_DISTORTION_CORRECTION 0,0,0,0,0,0,0,0,0,0
CAMERA_CONFIG_WIDE_DISTORTION_CORRECTION 0,0,0,0,0,0,0,0,0,0
CAMERA_CONFIG_WINE_DETECTOR OFF
CAMERA_GRAW_CONFIG_MFP_PIPELINE_MODE V1
GALLERY_CONFIG_AI_EXPANSION AI_Timelapse
GENAI_SUPPORT_TIME_WEATHER_WALLPAPER None
GRAPHICS_CONFIG_GAME_DEFAULT_FRAMERATE ${DEVICE_DISPLAY_REFRESH_RATE_VALUES_HZ:-60}
GRAPHICS_CONFIG_GAMEBOOSTER_MORE_HEAT 30
LCD_CONFIG_AOD_BRIGHTNESS_ANIMATION 0
LCD_CONFIG_AOD_FULLSCREEN 0
LCD_CONFIG_HW_MDNIE DDI
LCD_CONFIG_LOCAL_HBM 0
LCD_CONFIG_NATURAL_MODE_TYPE 0
LCD_CONFIG_PRIVACY_DISPLAY 0
LCD_CONFIG_VIVIDNESS 0
LCD_CONFIG_VIVIDPLUS 0
"

# [
# shellcheck disable=SC2094
APPLY_TARGET_FEATURE()
{
    local SOURCE_FILE="$WORKSPACE/system/system/etc/floating_feature.xml"
    local TARGET_FILE="$STOCK_FW/system/system/etc/floating_feature.xml"

    local FEATURE TAG_NAME SOURCE_VALUE TARGET_VALUE
    local SOURCE_FEATURES TARGET_FEATURES

    # Dynamically extract all unique feature tags from both XML files
    SOURCE_FEATURES="$(grep -o 'SEC_FLOATING_FEATURE_[A-Za-z0-9_]*' "$SOURCE_FILE" | sort -u)"
    TARGET_FEATURES="$(grep -o 'SEC_FLOATING_FEATURE_[A-Za-z0-9_]*' "$TARGET_FILE" | sort -u)"

    # Step 1: Process existing Workspace features
    for FEATURE in $SOURCE_FEATURES; do
        TAG_NAME="${FEATURE#SEC_FLOATING_FEATURE_}"

        # Skip blacklisted features (keeps workspace value untouched)
        if grep -q -w -E "(${FEATURE}|${TAG_NAME})" <<< "$BLACKLIST"; then
            continue
        fi

        SOURCE_VALUE="$(GET_FF_VAL "extra" "$FEATURE")"
        TARGET_VALUE="$(GET_FF_VAL "stock" "$FEATURE")"

        # Check FALLBACK if feature is missing in stock firmware
        if [ -z "$TARGET_VALUE" ]; then
            TARGET_VALUE="$(grep -w -E "(${FEATURE}|${TAG_NAME})" <<< "$FALLBACK" | sed -n 's/^[^ ]* //p')"
        fi

        # Remove feature if absent everywhere; update if value changed
        if [ -z "$TARGET_VALUE" ]; then
            FF "$FEATURE" ""
        elif [ "$SOURCE_VALUE" != "$TARGET_VALUE" ]; then
            FF "$FEATURE" "$TARGET_VALUE"
        fi
    done

    # Step 2: Port missing Target Stock features
    for FEATURE in $TARGET_FEATURES; do
        TAG_NAME="${FEATURE#SEC_FLOATING_FEATURE_}"

        # Ignore blacklisted or deprecated features
        if grep -q -w -E "(${FEATURE}|${TAG_NAME})" <<< "$BLACKLIST" || \
           grep -q -w -E "(${FEATURE}|${TAG_NAME})" <<< "$DEPRECATED"; then
            continue
        fi

        # Add feature if completely missing from workspace
        if ! grep -q -w "$FEATURE" <<< "$SOURCE_FEATURES"; then
            FF "$FEATURE" "$(GET_FF_VAL "stock" "$FEATURE")"
        fi
    done
}
# ]

LOG_BEGIN "- Applying target floating feature config"
ADD_FROM_FW "extra" "system" "etc/floating_feature.xml"
APPLY_TARGET_FEATURE
LOG_END

if [ -f "$PLATFORM_DIR/ff.sh" ]; then
    LOG_BEGIN "- Applying custom platform floating feature config"
    . "$PLATFORM_DIR/ff.sh"
    LOG_END
fi

if [ -f "$OBJECTIVE/ff.sh" ]; then
    LOG_BEGIN "- Applying custom device floating feature config"
    . "$OBJECTIVE/ff.sh"
    LOG_END
fi
